name: "(CD) (DEV)"

on:
  push:
    branches: ["dev"]
    # paths: ["**.ts", "**.tsx", "**.json"]

jobs:
  Running-On-Ubuntu:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Installing dependencies
        run: yarn install --prod

      - name: Building
        run: yarn build

      - name: Zipping project
        uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r onlytests.zip |
            node_modules
            ecosystem.config.js
            package.json
            projects
            scripts

      - name: SCP Command to Transfer Files
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIV_KEY }}
          source: "onlytests.zip"
          target: "~/"

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIV_KEY }}
          script: |
            unzip -qq onlytests.zip -d onlytests
            cd onlytests
            pm2 stop all
            pm2 start all
