name: "(CI) Main Workflow"

on:
  pull_request:
    types: [opened, synchronize]

env:
  NODE_VERSION: 18
  NODE_CACHE: "yarn"

jobs:
  LintingAndTesting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - name: NodeJS Config
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: ${{ env.NODE_CACHE }}

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Running Lint
        run: yarn lint

      - name: Running Tests
        run: yarn test --colors

  E2E:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - name: NodeJS Config
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: ${{ env.NODE_CACHE }}
          run: npm install pm2@latest -g

      - name: Caching build
        uses: actions/cache@v3.2.6
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

      - name: Run Cypress
        uses: cypress-io/github-action@v5.1.0
        with:
          config-file: projects/web/cypress.config.ts
          install-command: yarn install --prod
          build: yarn build
          start: yarn start
          browser: edge
