name: "(CD) (DEV)"

on:
  push:
    branches: ["dev"]
    # paths: ["**.ts", "**.tsx", "**.json"]

jobs:
  Running-On-Ubuntu:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIV_KEY }}
          script: |
            echo "Here we go!"
